USE BD_ClinicaInternacional

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF NOT EXISTS(SELECT column_name FROM information_schema.COLUMNS WHERE table_name ='TB_PACIENTE' AND column_name ='GA_Correo')
BEGIN
ALTER TABLE [dbo].TB_PACIENTE
ADD GA_Correo varchar(255) NULL
END   
GO
SET ANSI_PADDING OFF
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS(SELECT column_name FROM information_schema.COLUMNS WHERE table_name ='TB_ORDEN_HOSPITALIZACION' AND column_name ='GA_Procedencia')
BEGIN
ALTER TABLE [dbo].TB_ORDEN_HOSPITALIZACION
ADD GA_Procedencia int NULL
END   
GO
SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS(SELECT column_name FROM information_schema.COLUMNS WHERE table_name ='TB_HOJA_INGRESO_HOSPITALIZACION' AND column_name ='GA_CartaGarantia')
BEGIN
ALTER TABLE [dbo].TB_HOJA_INGRESO_HOSPITALIZACION
ADD GA_CartaGarantia INT NULL
END   
GO
SET ANSI_PADDING OFF
GO


--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO
--SET ANSI_PADDING ON
--GO

--IF  EXISTS(SELECT column_name FROM information_schema.COLUMNS WHERE table_name ='TB_CAMA' AND column_name ='ID_Hoja_Ingreso_Hospitalizacion')
--BEGIN
--	ALTER TABLE [TB_CAMA]
--	DROP CONSTRAINT FK_T_CL_ES_GO_Cama63
--	GO 
--	ALTER TABLE [TB_CAMA]
--	DROP COLUMN ID_Hoja_Ingreso_Hospitalizacion
--	GO
--END   
--GO
--SET ANSI_PADDING OFF
--GO


